language: en

pipeline:
  - name: SpacyNLP
  - name: SpacyTokenizer
  - name: SpacyFeaturizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100

policies:
- name: MemoizationPolicy
- name: KerasPolicy
  max_history: 3
  epochs: 200
  validation_split: 0.1
  random_seed: 1
- name: MappingPolicy
- name: EmbeddingPolicy    
- name: TwoStageFallbackPolicy
  nlu_threshold: 0.1
  ambiguity_threshold: 0.1
  core_threshold: 0.1
  fallback_core_action_name: "default_fallback"
  fallback_nlu_action_name: "default_fallback"
  deny_suggestion_intent_name: "out_of_scope"